version: '3.8'

services:

  db:
    image: postgres:16
    container_name: petlink-db
    restart: always
    environment:
      POSTGRES_DB: petlinkdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - petlinkdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: petlink-backend
    restart: always
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/petlinkdb
      DB_USERNAME: postgres
      DB_PASSWORD: root
      DDL_AUTO: update
      SHOW_SQL: false
    ports:
      - "8080:8080"

volumes:
  petlinkdata: