version: '3.8'

services:

  db:
    image: postgres:16
    container_name: petlink-db
    restart: always
    environment:
      POSTGRES_DB: petlinkdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - petlinkdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: petlink-backend
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/petlinkdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

volumes:
  petlinkdata: